### ISSUE TITLE
Support BigInt in idToChunks, idToPath and pathToId

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#163]
- Check if `BigInt` supported, use functions version that support it
- Otherwise use current implementation

Refs: https://github.com/metarhia/common/issues/147

**Comment by SemenchenkoVitaliy** [comment]
There is no problem with actual functions but, as I said earlier, eslint currently does not support BigInt:
```
/home/vitaliy/common/lib/id.js
  150:12  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap
  150:12  error  'BigInt' is not defined                                                                        no-undef

✖ 2 problems (2 errors, 0 warnings)
```
as well as metatests:
```
$ node test/all.js
/home/vitaliy/nodejs/common/node_modules/metatests/lib/case.js:73
          sResult = JSON.stringify(result);
                         ^

TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Object.metatests.case (/home/vitaliy/nodejs/common/node_modules/metatests/lib/case.js:73:26)
    at Object.<anonymous> (/home/vitaliy/nodejs/common/test/id.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
though BigInt.prototype.toString() does
```
$  node
> (BigInt(1234567890)).toString()
'1234567890'
```
so CI tests will fail in any case.
What should I do with that?

**Comment by SemenchenkoVitaliy** [comment]
Also we can temporary use
```javascript
BigInt.prototype.toJSON = function(){return this.toString()+'n'}
```
to stringify BigInt:
```
$ node
> BigInt.prototype.toJSON = function(){return this.toString()+'n'}
[Function]
> console.log(JSON.stringify({a:BigInt(123)}))
{"a":"123n"}
undefined
```
and
```javascript
JSON.parse('{"a": "123n"}', (key, value) => {
  if(typeof value === 'string' && value.lastIndexOf('n') === value.length - 1) {
    let i;
    for(i = 0; i < value.length - 1; i++) {
      if (value[i] !== '0' &&
          value[i] !== '1' &&
          value[i] !== '2' &&
          value[i] !== '3' &&
          value[i] !== '4' &&
          value[i] !== '5' &&
          value[i] !== '6' &&
          value[i] !== '7' &&
          value[i] !== '8' &&
          value[i] !== '9') return value;
    }
    return BigInt(value.slice(0, value.length - 1));
  }
  return value;
})
```
to parse it:
```
$ node
> JSON.parse('{"a": "123n"}', (key, value) => {
...   if(typeof value === 'string' && value.lastIndexOf('n') === value.length - 1) {
.....     let i;
.....     for(i = 0; i < value.length - 1; i++) {
.......       if (value[i] !== '0' &&
.........           value[i] !== '1' &&
.........           value[i] !== '2' &&
.........           value[i] !== '3' &&
.........           value[i] !== '4' &&
.........           value[i] !== '5' &&
.........           value[i] !== '6' &&
.........           value[i] !== '7' &&
.........           value[i] !== '8' &&
.........           value[i] !== '9') return value;
.......     }
.....     return BigInt(value.slice(0, value.length - 1));
.....   }
...   return value;
... })
{ a: 123n }
```

**Comment by SemenchenkoVitaliy** [comment]
Do we still need it? And what about `Uint64`, which we will use in future? If we do, I think it will be better to make separate functions for them.
BTW, `idToPath` and `idToChunks` are already compatible with both of them.
